obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.1,0.1], [0.1,-0.1],[-0.1,-0.1],[-0.1,0.1]]
#robot_radius: ir_of_robot
inflation_radius: 0.1

observation_sources: depth_img, depth_cloud

depth_img:  {sensor_frame: chassis, data_type: Image, topic: /depthcam/depth/image_raw, marking: true, clearing: true}
depth_cloud: {sensor_frame: chassis, data_type: PointCloud, topic: /depthcam/depth/points, marking: true, clearing: true}