local_costmap:
    global_frame: map
    robot_base_frame: robot_footprint
    update_frequency: 5.0
    publish_frequency: 2.0


    static_map: false
    rolling_window: true
    width: 3.0  
    height: 3.0
    resolution: 0.05

    plugins: 
        - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
        - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}

    static_layer:
        enabled:              true
        map_topic:            "/map"


    inflation_layer:
        enabled:              true
        cost_scaling_factor:  5
        inflation_radius:     0.3

    obstacle_layer:
        observation_sources: depth_cloud
        footprint_clearing_enabled: true
        depth_cloud: {sensor_frame: chassis, data_type: PointCloud, topic: /depthcam/depth/points, marking: true, clearing: true}