local_costmap:
    global_frame: odom
    robot_base_frame: robot_footprint
    update_frequency: 10
    publish_frequency: 10.0

    static_map: false
    rolling_window: true
    width: 3.0  
    height: 3.0
    resolution: 0.05

    plugins: 
        # - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
        - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}

    # static_layer:
    #     enabled:              true
    #     map_topic:            "/odom"


    inflation_layer:
        enabled:              true
        cost_scaling_factor:  5
        inflation_radius:     1

    obstacle_layer:
        observation_sources: laser_scan_sensor
        footprint_clearing_enabled: true
        laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}